//Apache NetBeans IDE 22
//Luis Felipe Spessoto - 2648016

public class FormPrincipal extends javax.swing.JFrame {

    

    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotPaginaInicial = new javax.swing.JLabel();
        barMenuPrincipal = new javax.swing.JMenuBar();
        mnEstoque = new javax.swing.JMenu();
        itMnOpcoesEstoque = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        itMnRelProds = new javax.swing.JMenuItem();
        itMnRelPessoas = new javax.swing.JMenuItem();
        mnCadPessoas = new javax.swing.JMenu();
        itMnCadFun = new javax.swing.JMenuItem();
        itMnCadForn = new javax.swing.JMenuItem();
        itMnCadCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotPaginaInicial.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        rotPaginaInicial.setText("Gerenciador de Estoque ");

        mnEstoque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnEstoque.setText("  Estoque  ");

        itMnOpcoesEstoque.setText("Abrir cadastro de estoque...");
        itMnOpcoesEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnOpcoesEstoqueActionPerformed(evt);
            }
        });
        mnEstoque.add(itMnOpcoesEstoque);

        barMenuPrincipal.add(mnEstoque);

        mnRelatorios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnRelatorios.setText("  Relatórios  ");

        itMnRelProds.setText("Relatório de produtos em estoque...");
        itMnRelProds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelProdsActionPerformed(evt);
            }
        });
        mnRelatorios.add(itMnRelProds);

        itMnRelPessoas.setText("Relatório de pessoas cadastradas...");
        itMnRelPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelPessoasActionPerformed(evt);
            }
        });
        mnRelatorios.add(itMnRelPessoas);

        barMenuPrincipal.add(mnRelatorios);

        mnCadPessoas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnCadPessoas.setText("  Cadastro de Pessoas  ");

        itMnCadFun.setText("Abrir cadastro de Funcionário...");
        itMnCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFunActionPerformed(evt);
            }
        });
        mnCadPessoas.add(itMnCadFun);

        itMnCadForn.setText("Abrir cadastro de Fornecedor...");
        itMnCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFornActionPerformed(evt);
            }
        });
        mnCadPessoas.add(itMnCadForn);

        itMnCadCliente.setText("Abrir cadastro de Cliente...");
        itMnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadClienteActionPerformed(evt);
            }
        });
        mnCadPessoas.add(itMnCadCliente);

        barMenuPrincipal.add(mnCadPessoas);

        setJMenuBar(barMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(rotPaginaInicial)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(rotPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnOpcoesEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnOpcoesEstoqueActionPerformed
        abrirOpcoesEstq();
    }//GEN-LAST:event_itMnOpcoesEstoqueActionPerformed

    private void itMnRelProdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelProdsActionPerformed
        abrirRelProd();
    }//GEN-LAST:event_itMnRelProdsActionPerformed

    private void itMnCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFornActionPerformed
        abrirCadFor();
    }//GEN-LAST:event_itMnCadFornActionPerformed

    private void itMnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadClienteActionPerformed
        abrirCadCli();
    }//GEN-LAST:event_itMnCadClienteActionPerformed

    private void itMnCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFunActionPerformed
        abrirCadFun();
    }//GEN-LAST:event_itMnCadFunActionPerformed

    private void itMnRelPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelPessoasActionPerformed
        abriRelPessoas();
    }//GEN-LAST:event_itMnRelPessoasActionPerformed

    public void abriRelPessoas(){
        FormRelPessoas.geraRelPes().setVisible(true);
    }
    
    public void abrirCadFun(){
        FormCadFuncio.geraCadFun().setVisible(true);
    }
    
    public void abrirCadFor(){
        FormCadForne.geraCadFor().setVisible(true);
    }
    
    public void abrirCadCli(){
        FormCadCliente.geraCadCliente().setVisible(true);
    }
    
    public void abrirRelProd(){
        FormRelProdutos.geraRelProd().setVisible(true);
    }
    
    public void abrirOpcoesEstq(){
        FormEstoqueProdutos.geraOpcoes().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenuPrincipal;
    private javax.swing.JMenuItem itMnCadCliente;
    private javax.swing.JMenuItem itMnCadForn;
    private javax.swing.JMenuItem itMnCadFun;
    private javax.swing.JMenuItem itMnOpcoesEstoque;
    private javax.swing.JMenuItem itMnRelPessoas;
    private javax.swing.JMenuItem itMnRelProds;
    private javax.swing.JMenu mnCadPessoas;
    private javax.swing.JMenu mnEstoque;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JLabel rotPaginaInicial;
    // End of variables declaration//GEN-END:variables
}
