
import javax.swing.JOptionPane;


//Luis Felipe Spessoto - 2648016
public class FormCompraProd extends javax.swing.JFrame {

    private GerenciamentoEstq gerEst = GerenciamentoEstq.geraEstq();
    private Produto p = new Produto();
    
    //MÉTODO SINGLETON
    private static FormCompraProd geraCompra;
    
    public FormCompraProd() {
        initComponents();
    }

    public static FormCompraProd geraCompraUnic(){
        if(geraCompra == null){
            geraCompra = new FormCompraProd();
        }
        return geraCompra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotNomeProd = new javax.swing.JLabel();
        rotCodProd = new javax.swing.JLabel();
        rotValorUnit = new javax.swing.JLabel();
        rotQuantProd = new javax.swing.JLabel();
        rotIdForn = new javax.swing.JLabel();
        rotIdFuncio = new javax.swing.JLabel();
        cxNomeProd = new javax.swing.JTextField();
        cxCodProd = new javax.swing.JTextField();
        cxValorUnit = new javax.swing.JTextField();
        cxQuantProd = new javax.swing.JTextField();
        cxIdForn = new javax.swing.JTextField();
        cxIdFuncio = new javax.swing.JTextField();
        btCadProd = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        rotCompra = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotNomeProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotNomeProd.setText("Nome do produto:");

        rotCodProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotCodProd.setText("Codigo do produto:");

        rotValorUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotValorUnit.setText("Valor unitario:");

        rotQuantProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotQuantProd.setText("Quantidade:");

        rotIdForn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotIdForn.setText("ID do fornecedor:");

        rotIdFuncio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotIdFuncio.setText("ID do funcionario:");

        cxValorUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxValorUnitActionPerformed(evt);
            }
        });

        btCadProd.setText("Cadastrar produto");
        btCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadProdActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar campos");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        rotCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotCompra.setText("Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rotIdForn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rotIdFuncio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rotValorUnit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rotNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxNomeProd)
                            .addComponent(cxCodProd)
                            .addComponent(cxValorUnit)
                            .addComponent(cxQuantProd)
                            .addComponent(cxIdForn)
                            .addComponent(cxIdFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rotCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rotCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotNomeProd)
                    .addComponent(cxNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotCodProd)
                    .addComponent(cxCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotQuantProd)
                    .addComponent(cxQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotIdForn)
                    .addComponent(cxIdForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotIdFuncio)
                    .addComponent(cxIdFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxValorUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxValorUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxValorUnitActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadProdActionPerformed
        comprarProdInserirLista();
    }//GEN-LAST:event_btCadProdActionPerformed

    public void limpar(){
        cxNomeProd.setText("");
        cxCodProd.setText("");
        cxValorUnit.setText("");
        cxQuantProd.setText("");
        cxIdForn.setText("");
        cxIdFuncio.setText("");
        cxNomeProd.requestFocus();
    }
    
    public void comprarProdInserirLista(){
        p = new Produto();
        try{
            p.setNome(cxNomeProd.getText());
        }
        catch(ProdMaxTamException pmt){
            pmt.impErrorExc();
            p = pmt.corrigirTamProd(p);
        }
        try{          
            p.setPreco(Integer.parseInt(cxValorUnit.getText()));
        }
        catch(PrecoNegException pre){
            pre.impErrorExc();
            p = pre.corrigirValorNeg(p);
        }
        try{
            p.setCodProduto(Integer.parseInt(cxCodProd.getText()));
            p.setQuantidade(Integer.parseInt(cxQuantProd.getText()));
            p.getFornecedor().setId(Integer.parseInt(cxIdForn.getText()));
            p.getFuncionario().setId(Integer.parseInt(cxIdFuncio.getText()));
        
            if(gerEst.consProdLista(p) == null){
                JOptionPane.showMessageDialog(
                        null,
                        "Produto cadastrado com sucesso!",
                        "Compra de produtos",
                        JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            }
            else{
                int resposta = JOptionPane.showConfirmDialog(
                null,
                "O produto com esse código já existe no estoque. Deseja atualizar a quantidade?",
                "Atualizar Produto",
                JOptionPane.YES_NO_OPTION
                );
                if (resposta == JOptionPane.YES_OPTION) {
                    gerEst.consProdLista(p).setQuantidade(gerEst.consProdLista(p).getQuantidade() + p.getQuantidade());
                    JOptionPane.showMessageDialog(
                        null,
                        "Quantidade do produto atualizada com sucesso!\nQuantidade atual: " + gerEst.consProdLista(p).getQuantidade(),
                        "Atualização Concluída",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                } else {
                    JOptionPane.showMessageDialog(
                        null,
                        "A quantidade do produto não foi alterada.",
                        "Operação Cancelada",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                }
                limpar();
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                null,
                "O valor unitario deve ser um inteiro!",
                "ERROR tipo de dados",
                JOptionPane.ERROR_MESSAGE
            );
            cxValorUnit.setText("");
            cxValorUnit.requestFocus();
        }
        p = gerEst.comprarProd(p);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCompraProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadProd;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxCodProd;
    private javax.swing.JTextField cxIdForn;
    private javax.swing.JTextField cxIdFuncio;
    private javax.swing.JTextField cxNomeProd;
    private javax.swing.JTextField cxQuantProd;
    private javax.swing.JTextField cxValorUnit;
    private javax.swing.JLabel rotCodProd;
    private javax.swing.JLabel rotCompra;
    private javax.swing.JLabel rotIdForn;
    private javax.swing.JLabel rotIdFuncio;
    private javax.swing.JLabel rotNomeProd;
    private javax.swing.JLabel rotQuantProd;
    private javax.swing.JLabel rotValorUnit;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
