
import javax.swing.JOptionPane;



//Luis Felipe Spessoto - 2648016
public class FormEstoqueProdutos extends javax.swing.JFrame {

    private GerenciamentoEstq gerEst = GerenciamentoEstq.geraEstq();
    
    //MÉTODO SINGLETON
    private static FormEstoqueProdutos opcoesUnicForm;
    
    public FormEstoqueProdutos() {
        initComponents();
    }

    public static FormEstoqueProdutos geraOpcoes(){
        if(opcoesUnicForm == null){
            opcoesUnicForm = new FormEstoqueProdutos();
        }
        return opcoesUnicForm;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorCima = new javax.swing.JSeparator();
        separadorBaixo = new javax.swing.JSeparator();
        rotOpcoesEstoque = new javax.swing.JLabel();
        btCompraEstq = new javax.swing.JButton();
        btVendaEstg = new javax.swing.JButton();
        btProcurarEstq = new javax.swing.JButton();
        btDeletarEstq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotOpcoesEstoque.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotOpcoesEstoque.setText("Escolha uma das opções:");

        btCompraEstq.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btCompraEstq.setText("Compra de produtos [de Fornecedores]");
        btCompraEstq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraEstqActionPerformed(evt);
            }
        });

        btVendaEstg.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btVendaEstg.setText("Venda de produtos [para Clientes]");
        btVendaEstg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaEstgActionPerformed(evt);
            }
        });

        btProcurarEstq.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btProcurarEstq.setText("Procurar produto");
        btProcurarEstq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarEstqActionPerformed(evt);
            }
        });

        btDeletarEstq.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btDeletarEstq.setText("Deletar Produto");
        btDeletarEstq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarEstqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separadorBaixo)
                            .addComponent(separadorCima))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rotOpcoesEstoque)
                        .addGap(124, 124, 124))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCompraEstq, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btVendaEstg, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                        .addComponent(btDeletarEstq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btProcurarEstq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rotOpcoesEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorCima, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btCompraEstq)
                .addGap(18, 18, 18)
                .addComponent(btVendaEstg)
                .addGap(18, 18, 18)
                .addComponent(btProcurarEstq)
                .addGap(18, 18, 18)
                .addComponent(btDeletarEstq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(separadorBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVendaEstgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaEstgActionPerformed
        abrirVendaProd();
    }//GEN-LAST:event_btVendaEstgActionPerformed

    private void btCompraEstqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraEstqActionPerformed
        abrirCompraProd();
    }//GEN-LAST:event_btCompraEstqActionPerformed

    private void btProcurarEstqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarEstqActionPerformed
        abrirProcuraProd();
    }//GEN-LAST:event_btProcurarEstqActionPerformed

    private void btDeletarEstqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarEstqActionPerformed
        delProd();
    }//GEN-LAST:event_btDeletarEstqActionPerformed

    public void delProd(){
        int codDeletar = Integer.parseInt(JOptionPane.showInputDialog(
                null, 
                "Informe o código do produto para ser deletado: ", 
                "Remoção de Produtos",
                JOptionPane.DEFAULT_OPTION));
        
        gerEst.deletarProduto(codDeletar);
    }
    
    
    public void abrirProcuraProd(){
        FormConsultaProd.geraConsultaUnic().setVisible(true);
    }
    public void abrirCompraProd(){
        FormCompraProd.geraCompraUnic().setVisible(true);
    }
    
    public void abrirVendaProd(){
        FormVendaProd.geraVendaUnic().setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEstoqueProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEstoqueProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEstoqueProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEstoqueProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEstoqueProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompraEstq;
    private javax.swing.JButton btDeletarEstq;
    private javax.swing.JButton btProcurarEstq;
    private javax.swing.JButton btVendaEstg;
    private javax.swing.JLabel rotOpcoesEstoque;
    private javax.swing.JSeparator separadorBaixo;
    private javax.swing.JSeparator separadorCima;
    // End of variables declaration//GEN-END:variables
}
