
import javax.swing.JOptionPane;


//Luis Felipe Spessoto - 2648016
public class FormConsultaProd extends javax.swing.JFrame {

    private GerenciamentoEstq gerEst = GerenciamentoEstq.geraEstq();
    private Produto p = new Produto();
    
    //MÉTODO SINGLETON
    private static FormConsultaProd geraConsulta;
    
    public FormConsultaProd() {
        initComponents();
    }

    public static FormConsultaProd geraConsultaUnic(){
        if(geraConsulta == null){
            geraConsulta = new FormConsultaProd();
        }
        return geraConsulta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotNomeProd = new javax.swing.JLabel();
        rotCodProd = new javax.swing.JLabel();
        rotValorUnit = new javax.swing.JLabel();
        rotQuantProd = new javax.swing.JLabel();
        rotIdForn = new javax.swing.JLabel();
        rotIdFuncio = new javax.swing.JLabel();
        cxCodProd = new javax.swing.JTextField();
        cxNomeProd = new javax.swing.JTextField();
        cxValorUnit = new javax.swing.JTextField();
        cxQuantProd = new javax.swing.JTextField();
        cxIdForn = new javax.swing.JTextField();
        cxIdFuncio = new javax.swing.JTextField();
        btCadProd = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        rotCompra = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        rotMensagemConsu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rotNomeProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotNomeProd.setText("Nome do produto:");

        rotCodProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotCodProd.setText("Codigo do produto:");

        rotValorUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotValorUnit.setText("Valor unitario:");

        rotQuantProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotQuantProd.setText("Quantidade:");

        rotIdForn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotIdForn.setText("ID do fornecedor:");

        rotIdFuncio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rotIdFuncio.setText("ID do funcionario:");

        cxCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCodProdActionPerformed(evt);
            }
        });

        cxValorUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxValorUnitActionPerformed(evt);
            }
        });

        btCadProd.setText("Procurar produto");
        btCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadProdActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar campos");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        rotCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rotCompra.setText("Procura");

        rotMensagemConsu.setText("Inserir código para consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rotIdForn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rotIdFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rotValorUnit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxValorUnit)
                            .addComponent(cxQuantProd)
                            .addComponent(cxIdForn)
                            .addComponent(cxIdFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rotCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotCodProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxCodProd)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cxNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rotMensagemConsu)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rotCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotMensagemConsu)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotCodProd)
                    .addComponent(cxCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotNomeProd)
                    .addComponent(cxNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotQuantProd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxIdForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotIdForn))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxIdFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotIdFuncio))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxValorUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxValorUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxValorUnitActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadProdActionPerformed
        procProdList();
    }//GEN-LAST:event_btCadProdActionPerformed

    private void cxCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCodProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCodProdActionPerformed

    public void limpar(){
        cxNomeProd.setText("");
        cxCodProd.setText("");
        cxValorUnit.setText("");
        cxQuantProd.setText("");
        cxIdForn.setText("");
        cxIdFuncio.setText("");
        cxCodProd.requestFocus();
    }
    
    public void procProdList(){
        p = new Produto();
        
        p.setCodProduto(Integer.parseInt(cxCodProd.getText()));
        p = gerEst.consProdLista(p);
        
        if(p != null){
            cxCodProd.setText(Integer.toString(p.getCodProduto()));
            cxNomeProd.setText(p.getNome());
            cxValorUnit.setText(Double.toString(p.getPreco()));
            cxQuantProd.setText(Integer.toString(p.getQuantidade()));
            cxIdForn.setText(Integer.toString(p.getFornecedor().getId()));
            cxIdFuncio.setText(Integer.toString(p.getFuncionario().getId()));
            
            JOptionPane.showMessageDialog(
                null,
                "Produto encontrado!",
                "Procura",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Produto não consta no estoque",
                "ERRO",
                JOptionPane.ERROR_MESSAGE
            );
            limpar();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCompraProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCompraProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadProd;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxCodProd;
    private javax.swing.JTextField cxIdForn;
    private javax.swing.JTextField cxIdFuncio;
    private javax.swing.JTextField cxNomeProd;
    private javax.swing.JTextField cxQuantProd;
    private javax.swing.JTextField cxValorUnit;
    private javax.swing.JLabel rotCodProd;
    private javax.swing.JLabel rotCompra;
    private javax.swing.JLabel rotIdForn;
    private javax.swing.JLabel rotIdFuncio;
    private javax.swing.JLabel rotMensagemConsu;
    private javax.swing.JLabel rotNomeProd;
    private javax.swing.JLabel rotQuantProd;
    private javax.swing.JLabel rotValorUnit;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
